# MAKE SURE TO USE \\ INSTEAD OF \.
# MAKE SURE THAT THE PATH OF "todo", "done"
# and "reject" is a directory WITH ONLY FOLDERS INSIDE
# NO OTHER FILES, ONLY FOLDER THIS WILL CAUSE ERROR!

# AFTER SAVING HIT THE REFRESH BUTTON TO APPLY THE CHANGES PERMANENTLY

todo=C:\\Users\\jahar\\OneDrive\\Desktop\\Fileuploader\\uploads\\Todo
done=C:\\Users\\jahar\\OneDrive\\Desktop\\Fileuploader\\uploads\\Done
reject=C:\\Users\\jahar\\OneDrive\\Desktop\\Fileuploader\\uploads\\Rejected
notif=C:\\Users\\jahar\\Downloads\\third.wav
